# Generated by Django 4.0.4 on 2022-04-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_medicating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicating',
            new_name='Medication',
        ),
    ]
