# Generated by Django 4.0.4 on 2022-04-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_medicating_medication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='medication',
            name='needs_meds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.DateField(verbose_name='Administration date'),
        ),
    ]
