# Generated by Django 4.0.4 on 2022-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_medication_options_medication_needs_meds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='needs_meds',
        ),
        migrations.AddField(
            model_name='animal',
            name='needs_meds',
            field=models.BooleanField(default=False),
        ),
    ]
