# Generated by Django 4.0.4 on 2022-04-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_medication_needs_meds_animal_needs_meds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zookeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
