# Generated by Django 4.0.4 on 2022-04-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_zookeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='zookeeper',
            name='animals',
            field=models.ManyToManyField(to='main_app.animal'),
        ),
    ]
